name: Build "Box64"

on:
  schedule:
  - cron: '0 8 * * 3'
permissions:
  contents: write

jobs:
  start_building_box64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt -y install git cmake make python3 patchelf zstd p7zip gcc-aarch64-linux-gnu -y
        export PATH=$PATH:/usr/aarch64-linux-gnu/bin
    - name: Execute build script
      run: bash ./build.sh

    - name: Release "Box64"
      uses: softprops/action-gh-release@v1
      with:
        body: box64 build arm64
        tag_name: box64new
        name: Release
        files: |
           /home/runner/work/box64_build_winlator/box64_build_winlator/box64/build/box64_w10_box32.tzst
           /home/runner/work/box64_build_winlator/box64_build_winlator/box64/build/box64_wp_box32.tzst
           /home/runner/work/box64_build_winlator/box64_build_winlator/box64/buildNo32/box64_wp.tzst
           /home/runner/work/box64_build_winlator/box64_build_winlator/box64/buildNo32/box64_w10.tzst
